#!/bin/bash

source ETCPREFIX/acpithings.rc

function susprep {
    logger -t suspend "sleeping down"
    for A in $(ls /media/); do pumount $A; done;
    $NET_DOWN
    sync
    logger -t suspend "sleeping now"
}

function suspres {
    logger -t suspend "waking up"
    $NET_UP
    if [ "$(</sys/class/power_supply/AC/online)" -ne 1 ]; then
        powerdown
    else
        powerup
    fi
    logger -t suspend "woken up"
}

susprep
if [ "$1" == "disk" ]; then
        echo -n disk >/sys/power/state
else
        echo -n mem >/sys/power/state
fi
suspres
